install.packages("devtools", repos="http://cran.rstudio.com/")
devtools::install_github( "gergness/srvyr" , dependencies = TRUE )
devtools::install_github( "djalmapessoa/convey" , dependencies = TRUE )
devtools::install_github( "ajdamico/lodown" , dependencies = TRUE )
devtools::install_github( "hannesmuehleisen/MonetDBLite" , dependencies = TRUE )
